dist: trusty

language: R
warnings_are_errors: true

sudo: required

r_packages:
  - covr

bioc_packages:
  - graph
  - RBGL
  - Rgraphviz

repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'