dist: trusty

language: R
warnings_are_errors: true

sudo: required

r_packages:
  - covr
  
apt_packages:
  - libcurl4-openssl-dev
  - libxml2-dev
  - libudunits2-dev

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 g++-5 gfortran-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100

install:
  - - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_bioc(c("graph","RBGL","Rgraphviz"))'
  - R -e 'devtools::install_deps(dep = T)'

repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'