dist: trusty

language: R
warnings_are_errors: true

sudo: required

r_packages:
  - assertthat
  - covr
  - igraph
  - Hmisc
  - pcalg
  - rvinecopulib
  - stats
  - utils
  - testthat

repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'